# Site settings
course_name: Knowledge Modelling and Semantic Web Technologies (AI60008)
course_description: "Knowledge modelling is a process of formalizing the knowledge of a domain through formal knowledge representation frameworks. Among many other knowledge driven systems, knowledge modelling through ontology has helped in embedding semantics to current hypertext-based web and several real-world applications from diverse domains. The semantic web vision has shown enormous promise to revolutionize current World Wide Web dramatically. This vision rides on the idea of embedding semantics of web data so that the contents become amenable to machine processing. Driving technologies in semantic web vision include explicit metadata, ontologies, formal logic, inferencing and intelligent agents. Huge potential and advantages of semantic web have sparked significant interest in industry and government. 
This course aims at developing foundations in semantic web technology addressing web scale semantic knowledge modelling techniques and related programming paradigms and application case studies.
"

course_semester: "Spring,2022-23"

baseurl: "/kmst-spring-2023" # the subpath of your site, e.g. /blog/
url: "http://ainimesh.github.io/" # the base hostname & protocol for your site

schoolname: "CoE-AI, IIT Kharagpur"
schoolurl: "http://www.ai.iitkgp.ac.in/"
#twitter_username: username 

address: |
    Center of Excellence in Artififial Intelligence
    IIT Kharagpur, 721302
    West Bengal, India

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"

theme: jekyll-theme-cayman
